title: 我的博客
description: "Zack 的学习与成长"
show_downloads: False
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
nav:
  - name: 归档
    link: /archive
